### ISSUE TITLE
Set the Stereo Volume to 20% DOES work

### ISSUE THREAD

**Issue by jer78** [robertvorthman/homebridge-marantz-volume#1]
not sure why you say it doesn't because it works for me. :) My accessory is named Stereo Volume and confirm it works now. Maybe there was a change on the backend Siri

**Comment by robertvorthman** [comment]
Thanks for letting me know.  I have updated the read me.  Siri must have gotten smarter recently.

**Comment by robertvorthman** [comment]
@jer78 
In the past few days, Siri has stopped responding to just "stereo volume" so now I have to say "stereo volume brightness" again.  Have you noticed that too?

**Comment by jer78** [comment]
Just tried it now and it still works for me. It is annoying however how Apple constantly changes Siri and messes things up. For instance I can no longer turn on my "TV" or "Apple TV" with my Harmony plugin but I can ask the state of it being on or off and that works fine. I sent a bug report to Apple already about this.

**Comment by robertvorthman** [comment]
Same here.  I have an accessory called "TV" and lately when I say "turn off the TV" Siri says she doesn't understand what a TV is.
