### ISSUE TITLE
Does not work with Denon AVR-X4300H

### ISSUE THREAD

**Issue by ssummer** [robertvorthman/homebridge-marantz-volume#13]
Had it working fine with my Denon AVR-X2200W, but it doesn't seem to work with my new AVR-X4300H. I also noticed that AVR-X4300H doesn't have a web UI for control and setup like the AVR-X2200W does - which is almost certainly why the plugin doesn't work - looking at the way the plugin works. The only web UI I can find is a basic, 3 page HEOS one - nothing with control settings.

**Comment by DSchumacher2104** [comment]
All new Denon HEOS Receiver don't react on http-commands. However, the telnet commands still work. Perhaps it is possible to switch the plugin using telnet commands to control the avr. You simlpy need to build up a telnet connection to AVR-IP and send the command "MVxx" xx=Volume Level in ASCII from 00 to 98. "MV?" returns the Main Zone Volume Level. This works also for older models. To control ZONE2 the telnet protocol uses the command "Z2xx".

**Comment by carloscae** [comment]
The do react on HTTP commands. Format is slightly different now.

http://IP:8080/goform/formiPhoneAppDirect.xml?MV60

**Comment by naartem** [comment]
Hi, I have it working on a newer model (AVR-X2400H) with the following settings and changes:
Use port number 8080 in the host ip:
`"host":           "192.168.1.15:8080"`

Next, edit the index.js and change the url in the getStatus function:
`Line 46:     var statusUrl = `http://${this.host}/goform/form${this.zoneName}_${this.zoneName}XmlStatus.xml`;`

Change line 46 to _(notice 'Lite' postfix in the filename)_:

`    var statusUrl = `http://${this.host}/goform/form${this.zoneName}_${this.zoneName}XmlStatus**Lite**.xml`;`

I believe this url is also working on the 'older' Denon AVR's, so maybe the @robertvorthman (or other dev) could change the code accordingly in the master branch?

**Comment by robertvorthman** [comment]
@naartem Thanks for finding the fix.  I have updated the package.  Please update and let me know how it works for you.  It's working for me on my old Marantz NR1605 circa 2014.

**Comment by carloscae** [comment]
Works like a charm on AVR-X1400 -> but you need to add the port number to the host.

**Comment by robertvorthman** [comment]
I have updated the readme to mention adding port 8080 to the host config.
