### ISSUE TITLE
Switch off when powered down

### ISSUE THREAD

**Issue by ObsidianPhoenix** [robertvorthman/homebridge-marantz-volume#17]
I’ve got this plugin successfully running, and using the 0%/off as the mute switch. This works great, but I was wondering if there’s some way for the switch to also show “off” whenever the Amp is powered down.

To be clear, I don’t want to use this plugin to control the power state, rather I’d like it to show as off when the amp is powered down, whilst still using the off toggle as a mute switch?

**Comment by robertvorthman** [comment]
Use this other plugin to show power state:
https://github.com/stfnhmplr/homebridge-denon-marantz-avr

**Comment by ObsidianPhoenix** [comment]
That’ll just show up as another control though right? I’ve got it tied into the Harmony plugin, so i’m not so worried about the state, its just the OCD in me that would like the volume control in HomeKit to disable when the amp is off.

I can live without it, especially since I want to use the power state for muting. Just trying to satisfy my need for neatness.
