### ISSUE TITLE
Mute issue

### ISSUE THREAD

**Issue by guysbrown** [robertvorthman/homebridge-marantz-volume#18]
Hey,

Just started using this plugin and love it.

I am using the On/Off state of the 'bulb' for muting the Marantz which is great but have found a little issue.

If the volume is set to, for example, 55% and I turn 'Off' the 'bulb' it puts the Marantz on Mute which is great. However if I then ask Siri to set the volume ('bulb') to 60% then the Marantz does unmute but the volume stays at 55% and is not set to the requested volume. Homekit then reports the volume ('brightness') to be 60% even though it is actually 55%.

Also, it would be great if the mute status (i.e. the bulb being On or Off) was reported as Off when the Marantz is off or on standby as it looks a little odd it being On when the receiver is Off.

Thanks

Guy

**Comment by huongminh** [comment]
Same from me. It would be great to have the volume synchronized with the Off status of the receiver. I can see that now when I turn on my Denon, the volume fan/bulb is on also, but not when the Denon if off.
