### ISSUE TITLE
Change in "Power" functionality

### ISSUE THREAD

**Issue by leoneleone** [robertvorthman/homebridge-marantz-volume#4]
I believe that the PowerState On/Off Characteristic of this plugin should be attributed to UnMuting/Muting the Volume, rather than handling power On/Off functions for the receiver. 

So ideally, "Stereo Volume" ON would unmute the marantz volume/audio, and "Stereo Volume" OFF would mute the marantz audio. 

This is a "Marantz Volume" plugin after all. The specificity of the PowerState functionality as I am envisioning it seems like a more logical approach. 

Any thoughts? 🙂

**Comment by robertvorthman** [comment]
That all makes sense but if you sit down to watch a movie and tell Siri to "turn off all the lights" then the movie volume would mute.  If there is enough interest I could make power state control an option.

For now I just use this homebridge plugin to control power state https://github.com/stfnhmplr/homebridge-denon-marantz-avr

**Comment by jer78** [comment]
I vote it would be nice to have as an option. Basically we run into the same problem if we say "dim all the lights to 20%" it also changes the volume to 20. 

The workaround I have is NOT to put this accessory in a room and then when changing lights etc I call them by room such as "dim the living room lights to 30%"

And if we are talking options, have either the mute as the on and off option or the power. Thanks for all your work on this. If homebridge was more documented I would pick up a project or two but I just don't have the time to learn so very much appreciate your time on this

**Comment by leoneleone** [comment]
@robertvorthman 
I understand what you're saying. But surely with the current setup you described, if you were to say turn off all the lights, then the plugin (as it is coded currently) would turn off the marantz receiver anyway. All that would happen if we were to use my approach is that the volume would be muted, even if HomeKit sees "Stereo Volume" as a light.

"Stereo Volume" ON = UnMute
"Stereo Volume" OFF = Mute

Also, I'm finding in the current iOS 10 beta build (beta 4), you can add the Brightness Characteristic to any ServiceType. I know that functionality stopped working for a while, but it is back now. Which means adding Brightness to a normal switch type, or any other service type, the Siri functionality will work with that service type. I have my Sonos plugin coded to use brightness to control my Sonos volume. Siri Commands still work, ex. "Set the living room Sonos to 60%", etc

Also, if this is at all helpful, I wouldn't tell Siri to turn off the living room lights or all the lights when I want to watch a movie. Simply create a scene called Movie Time, or something similar, add the actions of turning off the lights that you want to be turned off when you watch a movie. That way you can just say "Hey Siri, It's Movie Time", etc and you'll get the functionality that you wanted, regardless of whether "Stereo Volume" is seen as a HomeKit lightbulb or not.

**Comment by tomkludy** [comment]
If you are interested I could easily extend my pull request #6 to make the power state configurable, to either be ignored (the default), power on/off, or mute/unmute.

**Comment by leoneleone** [comment]
That would great!
All it would need is to substitute "PowerState" with "MuteState", and then "PowerOn" with either "MuteOff" or "MuteOn" - making sure that On/Off function is reverse so that in HomeKit  MarantzVolume On = Volume is muted, Off = Volume is unmuted

🙂

**Comment by leoneleone** [comment]
```
function ReceiverVolume(log, config) {
    this.log = log;

    this.name = config['name'] || "Receiver Volume";
    this.maxVolume = config['maxVolume'] || 70;
    this.host = config['host'];

    this.statusUrl = "/goform/formMainZone_MainZoneXml.xml";
    this.controlUrl = "/goform/formiPhoneAppVolume.xml";

    //this.powerState = 0;
    this.muteState = 0;

    if (!this.host) {
        this.log.warn('Config is missing host/IP of receiver');
        callback(new Error('No host/IP defined.'));
        return;
    }

}

ReceiverVolume.prototype.getPowerOn = function(callback) {
    this.log("Receiver Volume Mute state is %s", this.muteState = muteOff ? 1 : 0);
    callback(null, this.muteState);
}

ReceiverVolume.prototype.setPowerOn = function(muteOff, callback) {

    this.muteState = muteOff ? 1 : 0;
    this.log("Set receiver Volume Mute state to %s", this.muteState);
    callback(null);
}
```

**Comment by leoneleone** [comment]
@tomkludy 
any ideas about this? i'm still confused as to how to script the muteState function for getPowerOn/setPowerOn

do you happen to know what muteState/MuteOn I should be using?
I'd really prefer the On/Off function to control the Marantz muteState. Don't think you submitted that change as part of your last pull request.

you help is much appreciated

**Comment by jbree** [comment]
@leoneleone,
I had the same desire as you for the volume control. I forked the repo and modified the power state of the light to control mute. See here: (https://github.com/jbree/homebridge-marantz-volume). It's not on npm, so you'll have to clone and install from your local disk.

@robertvorthman,
I made this fork as a quick and dirty hack for my own purposes. If you're interested in adding the functionality, I'd like to clean up the code and make a pull request that allows power/mute/neither to be configurable. If that's agreeable to you, I would like your input on how you'd like the config option to be set up.

**Comment by robertvorthman** [comment]
@jbree 
Thanks.  Since there is already a `controlPower` option maybe stay consistent with another option like `controlMute`.  If both options are set to true then `controlPower` would override `controlMute` I guess.  Really it would make more sense to have just one option that decides what power does that could be either be either `undefined`, `mute`, or `power`, but to retain backwards compatibility with the existing `controlPower` maybe it's better to just make a new option.  Just do whatever is easiest, it's not mission critical code here, it's ok if things get a little messy since the scope of this plugin is so narrow.

**Comment by robertvorthman** [comment]
@jbree Thanks for your PR.  I published it to npm.
