### ISSUE TITLE
Volume Feedback

### ISSUE THREAD

**Issue by simonrb2000** [robertvorthman/homebridge-marantz-volume#5]
Hi, not sure if I have this setup correctly. If I turn my amp on it doesn't reflect this on the stereo volume - it stays off. If I turn stereo volume on, the volume/brightness is set to 0 or if it's been used recently it's set to the value it was last set. It doesn't grab the actual volume from my amp. So my amp might be at 50% but the stereo volume would be at 0 so when I slide it to turn up stereo volume my amp volume drops before it goes up. 

Hope that makes sense, I thought turning on the stereo volume would grab the current volume value/status from the amp. 

Cheers

**Comment by robertvorthman** [comment]
Thanks for the feedback.  Lately my devices haven't been updating the volume either, it could be an iOS 10 beta issue.  What you are describing is what I experience too, so I think you have it setup correctly.

**Comment by simonrb2000** [comment]
Ah that's good, it's pretty handy little plugin when using watchOS 3 and iOS 10. 

Thanks for the prompt reply!

**Comment by simonrb2000** [comment]
I have a plugin the communicates with domoticz and every so often it refreshes and grabs current values, maybe that could be implemented with the powering on as a force refresh. If I knew how to code I would give it a try myself lol.

**Comment by simonrb2000** [comment]
Scrap that, it seems to be updating now.
