### ISSUE TITLE
Change fake lightbulb to fake fan

### ISSUE THREAD

**Issue by MBarti** [robertvorthman/homebridge-marantz-volume#8]
It'd be so much easier if you changed the "fake lightbulb" to a "fake fan".
That way we caould have the on/off management turned on in the plugin and saying to Siri "Turn the lights off" would not turn off the AVR. ("Though turn the fan off" would, but way less people control their fans than lights with homekit, so this will be a much smaller issue).

It appears it's just 2 lines in the code: changing "Service.Lightbulb" to "Service.Fan" and "Brightness" to "RotationSpeed".

Best

**Comment by Sonsi79** [comment]
Any News about this Great idea?

**Comment by sjoerdloeve** [comment]
Maybe since iOS 11.4 is available it's even possible to change from fake lightbulb to speaker? Would be awesome.

**Comment by DanielWeeber** [comment]
https://github.com/DanielWeeber/homebridge-marantz-volume
Done. 
You can choose via option in config.js, PR #16 created.
